# Site-Informationen
title: "Alessia Valentina – Schweizer Eiskunstläuferin | Offizielle Website"
description: "Offizielle Website von Alessia Valentina: Erfolge im Eiskunstlauf, Sponsoring-Möglichkeiten und Kontakt."
url: "https://alessiavalentina.ch" # Deine Website-URL
baseurl: "" # Falls deine Seite in einem Unterverzeichnis liegt, z.B. "/blog"

# Sprach- und Lokalisierungseinstellungen
language: "de-CH"
locale: "de_CH"

# Plugins (optional, falls du SEO-Plugins verwenden möchtest)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Weitere Einstellungen
markdown: kramdown

# Navigation
navigation:
  - name: "Welcome"
    link: "#welcome"
    icon: "bi-info-circle-fill"
    aria_label: "Home"
  - name: "Sponsoring"
    link: "#sponsoring"
    icon: "bi-house-fill"
    aria_label: "Sponsoring"
  - name: "Top"
    link: "#"
    icon: "bi-arrow-up-circle-fill"
    aria_label: "Aktiv"
  - name: "Galerie"
    link: "#gallery"
    icon: "bi-images"
    aria_label: "Galerie"
  - name: "Contact"
    link: "#contact"
    icon: "bi-envelope-fill"
    aria_label: "Kontakt"

# Assets
assets:
  css: "https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.3/lux/bootstrap.min.css"
  icons: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
  js: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
